# Generated by Django 6.0.2 on 2026-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_remove_review_user_review_name_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='contact_number',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
