# Generated by Django 6.0.2 on 2026-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_eventbooking_contact_number_eventbooking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='category',
            field=models.CharField(choices=[('Wedding Event', 'Wedding Event'), ('Birthday Party', 'Birthday Party'), ('Engagement Event', 'Engagement Event'), ('Corporate Event', 'Corporate Event'), ('Anniversary Event', 'Anniversary Event'), ('Festival Event', 'Festival Event'), ('Concert Event', 'Concert Event'), ('Baby Shower', 'Baby Shower'), ('Farewell Party', 'Farewell Party'), ('SchoolCollege Event', 'SchoolCollege Event'), ('House Warming', 'House Warming'), ('Cultural Program', 'Cultural Program')], max_length=100),
        ),
    ]
