# Generated by Django 6.0.2 on 2026-05-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_alter_eventbooking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='package',
            field=models.CharField(choices=[('Silver Package', 'Silver Package'), ('Gold Package', 'Gold Package'), ('Platinum Package', 'Platinum Package'), ('Diamond Package', 'Diamond Package'), ('Royal Package', 'Royal Package'), ('Wedding Premium', 'Wedding Premium')], max_length=100),
        ),
    ]
